import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import time

# --- CONFIGURATION & DETECTION ---
script_dir = os.path.dirname(os.path.abspath(__file__))
# Locate metadata generated by the C++ engine
meta_path = os.path.normpath(os.path.join(script_dir, "..", "output", "metadata.txt"))

# --- NEW METADATA PARSER ---
if os.path.exists(meta_path):
    with open(meta_path, 'r') as f:
        lines = f.readlines()
        # Line 1: The Model (e.g., HISTORICAL, GBM)
        CURRENT_MODEL_NAME = lines[0].strip() if len(lines) > 0 else "UNKNOWN"
        # Line 2: The File Path (e.g., data/ETHUSDT-trades-2022-01.bin)
        # We use os.path.basename to drop "data/" and replace to drop ".bin"
        FILE_TAG = os.path.basename(lines[1].strip()).replace('.bin', '') if len(lines) > 1 else "DATA"
    print(f"Auto-detected Market Model: {CURRENT_MODEL_NAME} | Source: {FILE_TAG}")
else:
    CURRENT_MODEL_NAME = "UNKNOWN"
    FILE_TAG = "UNKNOWN"

is_historical = (CURRENT_MODEL_NAME == "HISTORICAL")

# Binary layout must match the C++ Struct (48 bytes per trade)
trade_dtype = np.dtype([
    ('simId', np.uint32),
    ('padding1', np.uint32),
    ('buyerId', np.uint64),
    ('sellerId', np.uint64),
    ('price', np.int64),
    ('quantity', np.uint32),
    ('padding2', np.uint32),
    ('timestamp', np.int64)
])

file_path = os.path.normpath(os.path.join(script_dir, "..", "output", "trades_binary.dat"))
if not os.path.exists(file_path):
    print(f"Error: {file_path} not found.")
    exit()

# 1. MEMORY MAPPING
# Map the file to virtual memory without loading it fully into physical RAM yet
file_size_gb = os.path.getsize(file_path) / (1024**3)
print(f"Memory-mapping {file_size_gb:.2f} GB of binary data...")
start_time = time.time()
mmap_data = np.memmap(file_path, dtype=trade_dtype, mode='r')

total_trades = len(mmap_data)
print(f"Successfully linked {total_trades:,} trades.")

# 2. BIG DATA STRATEGY: STRIDED SAMPLING
# We define a maximum resolution to prevent plotting millions of redundant points
MAX_PLOT_POINTS = 500_000 
sample_step = max(1, total_trades // MAX_PLOT_POINTS)

print(f"Applying big data sampling (Step: {sample_step})...")

# --- CRITICAL PERFORMANCE FIX ---
# We force an explicit copy of the sampled slice into physical RAM.
# This prevents Matplotlib from constantly hitting the disk (Random I/O)
# during axis calculations and rendering.
sampled_prices = np.array(mmap_data['price'][::sample_step]).copy()

# Print RAM usage of the sampled array (Should be only a few MBs)
sampled_mem_mb = sampled_prices.nbytes / (1024**2)
print(f"Sampled data loaded into RAM: {sampled_mem_mb:.2f} MB")

# 3. DASHBOARD INITIALIZATION
fig = plt.figure(figsize=(22, 14))
gs = fig.add_gridspec(2, 2, width_ratios=[4, 1], height_ratios=[2.5, 1.2])

# --- UPDATED DASHBOARD TITLE ---
fig.suptitle(f'MotorHFT: Big Data Analytics | Model: {CURRENT_MODEL_NAME} | Asset: {FILE_TAG}', fontsize=24, fontweight='bold')

ax_paths = fig.add_subplot(gs[0, 0])
ax_hist = fig.add_subplot(gs[0, 1], sharey=ax_paths)
ax_disp = fig.add_subplot(gs[1, 0], sharex=ax_paths)
ax_metrics = fig.add_subplot(gs[1, 1])
ax_metrics.axis('off')

# 4. PLOTTING (ULTRA FAST)
# Since sampled_prices is now a standard RAM array, this will be nearly instant
ax_paths.plot(sampled_prices, color='midnightblue', linewidth=1.5, alpha=0.8)
ax_paths.set_title('Price Action (Sampled Stream)', fontsize=16)
ax_paths.set_ylabel('Price (Ticks)')
ax_paths.grid(True, alpha=0.3)

# 5. STATISTICS & DISPERSION
# Histogram of the price distribution based on the sampled data
ax_hist.hist(sampled_prices, bins=100, orientation='horizontal', color='darkorange', alpha=0.7)
ax_hist.set_title('Price Distribution')

# Lower panel: Detailed timeline dispersion
ax_disp.plot(sampled_prices, color='black', linewidth=1, label='Market Path')
ax_disp.set_title('Market Sequence Timeline')
ax_disp.set_xlabel(f'Sampled Step ({sample_step} trades per point)')

# 6. SUMMARY METRICS
metrics_text = (
    f"--- BIG DATA REPORT ---\n\n"
    f"Asset Source:      {FILE_TAG}\n"
    f"Total Data Scanned:{file_size_gb:.2f} GB\n"
    f"Total Trades:      {total_trades:,}\n"
    f"Sampled Points:    {len(sampled_prices):,}\n"
    f"Sampling Ratio:    1 : {sample_step}\n\n"
    f"--- PRICE INFO (Ticks) ---\n\n"
    f"Initial Price:     {sampled_prices[0]:,.2f}\n"
    f"Last Price:        {sampled_prices[-1]:,.2f}\n"
    f"Max Observed:      {sampled_prices.max():,.2f}\n"
    f"Min Observed:      {sampled_prices.min():,.2f}\n\n"
    f"Total Latency:     {time.time() - start_time:.2f}s"
)

ax_metrics.text(0.1, 0.9, metrics_text, fontsize=14, fontfamily='monospace', 
                verticalalignment='top', bbox=dict(boxstyle='round,pad=1', facecolor='#f8f9fa', edgecolor='gray'))

# --- UPDATED DYNAMIC IMAGE SAVING ---
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
output_img = os.path.join(script_dir, "..", "output", f"report_{FILE_TAG}_{CURRENT_MODEL_NAME}.png")
plt.savefig(output_img, dpi=150)

print(f"Analysis Complete! Multi-panel report saved: {output_img}")