// main.cpp

#include <iostream>
#include <chrono>
#include <thread>
#include <pthread.h>
#include <atomic>
#include <fstream>
#include <filesystem>
#include "OrderBook.hpp"
#include "MarketSimulator.hpp"
#include "MonteCarloSimulator.hpp"
#include "RingBuffer.hpp"
#include "HistoricalParser.hpp"
#include "BinaryParser.hpp"
#include "AssetPolicies.hpp"

void pinThread(int core_id) {
#if defined(__linux__)
    cpu_set_t cpuset;
    CPU_ZERO(&cpuset);
    CPU_SET(core_id, &cpuset);
    pthread_setaffinity_np(pthread_self(), sizeof(cpu_set_t), &cpuset);
#endif
}

int main() {
    OrderBook<ETH_Policy> myBook;
    RingBuffer<MarketEvent, 4194304> eventBuffer; 
    RingBuffer<Trade, 4194304> tradeBuffer; 
    myBook.setTradeBuffer(&tradeBuffer); 

    // =========================================================================
    // --- MASTER TOGGLE: HISTORICAL (BINARY) VS MONTE CARLO ---
    // =========================================================================
    // Set to 'true' to replay real Binance binary data (1 timeline).
    // Set to 'false' to run mathematical Monte Carlo universes (1000 timelines).

    bool RUN_HISTORICAL = true;

    // =========================================================================


    // =========================================================================
    // --- BINARY FILE TO OBTAIN THE DATA ---
    // =========================================================================
    // Set the relative route "data/filename.bin" to process the file

    std::string binFilename = "data/ETH_FULL_2024.bin";

    // =========================================================================



    // --- Monte Carlo parameters ---
    const uint32_t numOrdersPerSim = 1000000; // Total orders per simulation path
    const uint32_t NUM_SIMULATIONS = 1000;    // Number of parallel realities
    
    // Choose the Reality (Uncomment ONLY ONE):
    MarketModel currentModel = MarketModel::GBM;
    // MarketModel currentModel = MarketModel::MEAN_REVERSION;
    // MarketModel currentModel = MarketModel::JUMP_DIFFUSION;
    // MarketModel currentModel = MarketModel::CAUCHY;
    // MarketModel currentModel = MarketModel::TRENDING;

    // Ensure output directory exists and initialize data file
    std::filesystem::create_directories("output");
    std::ofstream initFile("output/trades_binary.dat", std::ios::binary | std::ios::trunc);
    initFile.close();

    auto startGlobal = std::chrono::high_resolution_clock::now();

    if (RUN_HISTORICAL) {
        // =========================================================================
        // 1. HISTORICAL REPLAY MODE (Single Timeline - PURE BINARY)
        // =========================================================================
        // Target the optimized binary file generated by PreCompiler.cpp

        std::cout << "=======================================" << std::endl;
        std::cout << "--- STARTING BINARY DATA ENGINE ---" << std::endl;
        std::cout << "Target: " << binFilename << std::endl;
        std::cout << "=======================================\n" << std::endl;

        myBook.setSimId(0); // Timeline 0 (The Real World)
        myBook.reset();

        std::atomic<bool> producerDone{false};
        std::atomic<bool> consumerDone{false};
        std::atomic<uint64_t> totalTradesLogged{0};

        // THREAD 1: PRODUCER (Pure Binary Ingestion)
        std::thread producer([&]() {
            pinThread(0); 
            BinaryParser::feedFromBinary(eventBuffer, binFilename);
            producerDone.store(true, std::memory_order_release);
        });

        // THREAD 2: CONSUMER (Matching Engine)
        std::thread consumer([&]() {
            pinThread(2); 
            MarketEvent ev;
            bool running = true;
            while (running) {
                if (eventBuffer.pop(ev)) {
                    if (ev.type == EventType::NEW_ORDER) myBook.addOrder(ev.order);
                    else if (ev.type == EventType::CANCEL_ORDER) myBook.cancelOrder(ev.order.id);
                    else if (ev.type == EventType::TERMINATE) running = false;
                } else { __builtin_ia32_pause(); }
            }
            consumerDone.store(true, std::memory_order_release);
        });

        // THREAD 3: ASYNC LOGGER (Binary Batch Writer)
        std::thread logger([&]() {
            pinThread(4); 
            std::ofstream file("output/trades_binary.dat", std::ios::binary | std::ios::app);
            Trade t;
            uint64_t tradeCount = 0;
            std::vector<Trade> batchBuffer;
            batchBuffer.reserve(10000); // Write in chunks of 10,000 for maximum SSD throughput
            
            while (!consumerDone.load(std::memory_order_acquire) || tradeCount > 0) {
                if (tradeBuffer.pop(t)) {
                    batchBuffer.push_back(t);
                    tradeCount++;
                    if (batchBuffer.size() >= 10000) {
                        file.write(reinterpret_cast<const char*>(batchBuffer.data()), batchBuffer.size() * sizeof(Trade));
                        batchBuffer.clear();
                    }
                } else {
                    if (consumerDone.load(std::memory_order_acquire)) break;
                    __builtin_ia32_pause();
                }
            }
            // Flush any remaining trades in the buffer
            if (!batchBuffer.empty()) {
                file.write(reinterpret_cast<const char*>(batchBuffer.data()), batchBuffer.size() * sizeof(Trade));
            }
            totalTradesLogged.store(tradeCount, std::memory_order_release);
            file.close();
        });

        producer.join(); 
        consumer.join(); 
        logger.join();

        auto endGlobal = std::chrono::high_resolution_clock::now();
        std::chrono::duration<double> elapsed = endGlobal - startGlobal;

        // Save metadata as HISTORICAL for the Python Visualizer script
        std::ofstream meta("output/metadata.txt");
        meta << "HISTORICAL\n" << binFilename;
        meta.close();

        uint64_t finalTrades = totalTradesLogged.load();
        std::cout << "\n--- BINARY REPLAY COMPLETE ---" << std::endl;
        std::cout << "Total Realities:           1 (The Real World)" << std::endl;
        std::cout << "Total Trades Logged:       " << finalTrades << std::endl;
        std::cout << "Elapsed time:              " << elapsed.count() << " seconds" << std::endl;
        std::cout << "Average Throughput:        " << (finalTrades / elapsed.count()) << " ops/sec" << std::endl;
        std::cout << "Metadata saved:            HISTORICAL -> output/metadata.txt" << std::endl;
        std::cout << "----------------------------------" << std::endl;

    } else {
        // =========================================================================
        // 2. MONTE CARLO MODE (Mathematical Multi-Path Engine)
        // =========================================================================
        
        // Figure out the model name BEFORE we start so we can print it
        std::string modelName;
        switch(currentModel) {
            case MarketModel::GBM:            modelName = "GBM"; break;
            case MarketModel::MEAN_REVERSION: modelName = "MEAN_REVERSION"; break;
            case MarketModel::JUMP_DIFFUSION: modelName = "JUMP_DIFFUSION"; break;
            case MarketModel::CAUCHY:         modelName = "CAUCHY"; break;
            case MarketModel::TRENDING:       modelName = "TRENDING"; break;
        }

        std::cout << "=======================================" << std::endl;
        std::cout << "--- STARTING MONTE CARLO SIMULATION ---" << std::endl;
        std::cout << "Model: " << modelName << " | Paths: " << NUM_SIMULATIONS << std::endl;
        std::cout << "=======================================\n" << std::endl;

        std::atomic<uint64_t> totalTradesGlobal{0};

        for (uint32_t sim = 0; sim < NUM_SIMULATIONS; ++sim) {
            std::cout << "Running Simulation " << sim + 1 << " / " << NUM_SIMULATIONS << "...\r" << std::flush;
            
            myBook.setSimId(sim);
            myBook.reset();

            std::atomic<bool> producerDone{false};
            std::atomic<bool> consumerDone{false};
            std::atomic<uint64_t> totalTradesSim{0};

            // THREAD 1: PRODUCER (Stochastic Engine)
            std::thread producer([&]() {
                pinThread(0); 
                MonteCarloSimulator::generateFlow(eventBuffer, numOrdersPerSim, 90, currentModel);
                producerDone.store(true, std::memory_order_release);
            });

            // THREAD 2: CONSUMER (Matching Engine)
            std::thread consumer([&]() {
                pinThread(2); 
                MarketEvent ev;
                bool running = true;
                while (running) {
                    if (eventBuffer.pop(ev)) {
                        if (ev.type == EventType::NEW_ORDER) myBook.addOrder(ev.order);
                        else if (ev.type == EventType::CANCEL_ORDER) myBook.cancelOrder(ev.order.id);
                        else if (ev.type == EventType::TERMINATE) running = false;
                    } else { __builtin_ia32_pause(); }
                }
                consumerDone.store(true, std::memory_order_release);
            });

            // THREAD 3: ASYNC LOGGER (Binary Batch Writer)
            std::thread logger([&]() {
                pinThread(4); 
                std::ofstream file("output/trades_binary.dat", std::ios::binary | std::ios::app);
                Trade t;
                uint64_t tradeCount = 0;
                std::vector<Trade> batchBuffer;
                batchBuffer.reserve(10000);
                
                while (!consumerDone.load(std::memory_order_acquire) || tradeCount > 0) {
                    if (tradeBuffer.pop(t)) {
                        batchBuffer.push_back(t);
                        tradeCount++;
                        if (batchBuffer.size() >= 10000) {
                            file.write(reinterpret_cast<const char*>(batchBuffer.data()), batchBuffer.size() * sizeof(Trade));
                            batchBuffer.clear();
                        }
                    } else {
                        if (consumerDone.load(std::memory_order_acquire)) break;
                        __builtin_ia32_pause();
                    }
                }
                if (!batchBuffer.empty()) {
                    file.write(reinterpret_cast<const char*>(batchBuffer.data()), batchBuffer.size() * sizeof(Trade));
                }
                totalTradesSim.store(tradeCount, std::memory_order_release);
                file.close();
            });

            producer.join(); 
            consumer.join(); 
            logger.join();
            
            totalTradesGlobal += totalTradesSim.load();
        }

        // Save metadata for Python based on the selected enum
        std::ofstream meta("output/metadata.txt");
        meta << modelName;
        meta.close();

        auto endGlobal = std::chrono::high_resolution_clock::now();
        std::chrono::duration<double> elapsed = endGlobal - startGlobal;

        uint64_t totalOrders = static_cast<uint64_t>(numOrdersPerSim) * NUM_SIMULATIONS;

        std::cout << "\n\n--- MONTE CARLO SIMULATION COMPLETE ---" << std::endl;
        std::cout << "Model Simulated:           " << modelName << std::endl;
        std::cout << "Total Realities Simulated: " << NUM_SIMULATIONS << std::endl;
        std::cout << "Total Orders Processed:    " << totalOrders << std::endl;
        std::cout << "Total Trades Logged:       " << totalTradesGlobal.load() << std::endl;
        std::cout << "Elapsed time:              " << elapsed.count() << " seconds" << std::endl;
        std::cout << "Average Throughput:        " << (totalOrders / elapsed.count()) << " ops/sec" << std::endl;
        std::cout << "Metadata saved:            " << modelName << " -> output/metadata.txt" << std::endl;
        std::cout << "---------------------------------------" << std::endl;
    }

    // =========================================================================
    // --- AUTOMATIC VISUALIZATION ---
    // =========================================================================
    std::cout << "Launching Visualizer..." << std::endl;
    
    // The command depends on if you are on Windows or Linux/WSL. 
    // For WSL/Linux we use python3:
    int result = std::system("python3 scripts/visualizer.py");
    
    if (result == 0) {
        std::cout << "Visualizer executed successfully." << std::endl;
    } else {
        std::cerr << "Visualizer failed to execute." << std::endl;
    }

    return 0;
}

// =========================================================================
// QUICK TERMINAL COMMANDS (WSL / LINUX)
// =========================================================================
// 1. Build:                            cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
// 2. Run:                              cmake --build build -j $(nproc) && ./build/MotorHFT
// 3. Download:                         python3 scripts/downloader.py
// 4. Download without terminal open:   nohup python3 scripts/downloader.py &
// 5. Tracking nohup:                   tail -f nohup.out
// =========================================================================

// =========================================================================
// HOW TO PRECOMPILE THE FILES (WSL / LINUX)
// =========================================================================
// 1. g++ -O3 src/PreCompiler.cpp -o precompiler
// 2. ./precompiler "NAME.csv" "NAME.bin"
// =========================================================================